import { Layout } from "@/components/layout/layout"
import '@/styles/globals.css'

export const metadata = {
  title: 'Site.set - Landing Page e Blog',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  )
}
