services:
  postgres:
    image: postgres:18
    container_name: petshop-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: petshop
      POSTGRES_PASSWORD: petshop
      POSTGRES_DB: petshop
    volumes: 
      - ./pgdata:/var/lib/postgresql

volumes:
  pgdata: 