import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google';

const interFont = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="pt-BR" className={interFont.className}>
      <body className="bg-navy-950 text-navy-50 antialiased">{children}</body>
    </html>
  );
}
